baseurl = "https://ayoubmah.github.io/"
publishDir = "public"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
pagerSize = 10


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Thoughts, notes, projects wa AchyaO Okhra ..."
  disableReadOtherPosts = false
  enableSharingButtons = true
  enableGlobalLanguageMenu = true
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[params.favicon]
  mask = "/favicon.png"
  msapplication = "/favicon.png"
  shortcut = "/favicon.png"


[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Ayoub's Blog"
    keywords = "tech, personal, blog"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]
    subtitle  = "Thoughts, notes,projects wa AchyaO Okhra ..."

    [languages.en.params.logo]
      logoText = "El-Mahjouby"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
